import { jsPDF } from 'jspdf';
import { pdfAccentStatRow, pdfBarChart, pdfBrandedHeader, pdfReportFooter, pdfSectionTitle, pdfSimpleTable, PDF_DANGER, PDF_OK, PDF_PALETTE, PDF_WARN } from '../../../shared/lib/pdfReport';
import { fmtLongDate, today } from '../../../shared/lib/format';
import { missingKycFieldLabels } from './contractFieldResolver';
import type { Contract, ContractGeneration, ContractRequest, ContractTemplate, Lead } from '../../../types/domain';

// CONTRACT_OF_SALE_BLUEPRINT.md §11 -- the 6 named reports, all through
// the shared branded-report toolkit (shared/lib/pdfReport.ts) every other
// report this session already uses, same page shape (KPI strip -> trend/
// chart -> detailed table -> exceptions -> footer). Every number here is
// read straight from real rows (contract_requests/contracts/
// contract_generations/contract_templates/leads) -- nothing simulated.

interface ReportHeaderInput {
  generatedByName: string;
  companyName: string | null | undefined;
  logoDataUri: string | null;
}

function newReportDoc(title: string, subtitle: string, h: ReportHeaderInput): { doc: jsPDF; y: number; pageW: number } {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const rightLines = [`Generated by ${h.generatedByName}`, new Date().toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })];
  let y = pdfBrandedHeader(doc, title, subtitle, rightLines, h.logoDataUri);
  y += 6;
  return { doc, y, pageW };
}

function finish(doc: jsPDF, companyName: string | null | undefined): jsPDF {
  pdfReportFooter(doc, companyName);
  return doc;
}

// `created_at`/`fulfilled_at` are full ISO timestamps (unlike this app's
// plain-date fields), so this diffs them directly rather than reusing
// shared/lib/format's own daysSince() (which assumes a bare YYYY-MM-DD
// and would mis-parse a full timestamp).
function daysBetween(fromIso: string, toIso: string): number {
  return Math.max(0, Math.round((new Date(toIso).getTime() - new Date(fromIso).getTime()) / 86400000));
}

// 1. Contract production report -- overall generation volume, the
// template-based/legacy split (both real: every generation, template-
// based or not, inserts a `contracts` row; only template-based ones ALSO
// get a `contract_generations` snapshot row -- so contracts.length is the
// true all-time total and generations.length is the template-based
// subset), a 6-month trend, and the most recent contracts produced.
export function buildContractProductionReport(contracts: Contract[], generations: ContractGeneration[], h: ReportHeaderInput): jsPDF {
  const { doc, y: y0, pageW } = newReportDoc('CONTRACT PRODUCTION REPORT', `All-time, as of ${fmtLongDate(today())}`, h);
  let y = y0;

  const templateBased = generations.length;
  const legacy = Math.max(0, contracts.length - templateBased);
  y = pdfSectionTitle(doc, y, pageW, 'Production summary');
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'Total contracts generated', value: contracts.length, accent: PDF_OK },
    { label: 'From a published template', value: templateBased, accent: PDF_WARN },
    { label: 'Legacy document', value: legacy },
  ]);

  const months: { key: string; label: string }[] = [];
  const now = new Date();
  for (let i = 5; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    months.push({ key: `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`, label: d.toLocaleDateString('en-GB', { month: 'short' }) });
  }
  const byMonth = new Map(months.map((m) => [m.key, 0]));
  for (const c of contracts) {
    const key = c.createdAt.slice(0, 7);
    if (byMonth.has(key)) byMonth.set(key, (byMonth.get(key) ?? 0) + 1);
  }
  y = pdfSectionTitle(doc, y, pageW, 'Last 6 months');
  y = pdfBarChart(
    doc,
    12,
    y,
    pageW - 24,
    38,
    months.map((m, i) => ({ label: m.label, value: byMonth.get(m.key) ?? 0, color: PDF_PALETTE[i % PDF_PALETTE.length] }))
  );

  const recent = [...contracts].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 20);
  y = pdfSectionTitle(doc, y, pageW, 'Most recent', `${recent.length} of ${contracts.length}`);
  y = pdfSimpleTable(doc, y, pageW, ['CLIENT', 'GENERATED BY', 'DATE'], recent.map((c) => [c.clientName, c.createdByName, c.createdAt.slice(0, 10)]), [0.4, 0.35, 0.25]);

  return finish(doc, h.companyName);
}

// 2. Outstanding requests report -- every real pending contract_request,
// aged by createdAt, oldest first.
export function buildOutstandingRequestsReport(requests: ContractRequest[], h: ReportHeaderInput): jsPDF {
  const { doc, y: y0, pageW } = newReportDoc('OUTSTANDING CONTRACT REQUESTS', `As of ${fmtLongDate(today())}`, h);
  let y = y0;

  const nowIso = new Date().toISOString();
  const pending = requests.filter((r) => r.status === 'pending').map((r) => ({ ...r, ageDays: daysBetween(r.createdAt, nowIso) })).sort((a, b) => b.ageDays - a.ageDays);
  const avgAge = pending.length ? Math.round(pending.reduce((s, r) => s + r.ageDays, 0) / pending.length) : 0;

  y = pdfSectionTitle(doc, y, pageW, 'Summary');
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'Pending requests', value: pending.length, accent: pending.length ? PDF_WARN : PDF_OK },
    { label: 'Oldest pending (days)', value: pending[0]?.ageDays ?? 0 },
    { label: 'Average age (days)', value: avgAge },
  ]);

  y = pdfSectionTitle(doc, y, pageW, 'Pending requests', 'oldest first');
  y = pdfSimpleTable(
    doc,
    y,
    pageW,
    ['CLIENT', 'REQUESTED BY', 'REQUESTED', 'AGE (DAYS)'],
    pending.map((r) => [r.clientName, r.requestedByName, r.createdAt.slice(0, 10), String(r.ageDays)]),
    [0.35, 0.3, 0.2, 0.15]
  );

  const overdue = pending.filter((r) => r.ageDays > 7);
  if (overdue.length) {
    y = pdfSectionTitle(doc, y, pageW, 'Exceptions', `${overdue.length} pending more than 7 days`);
    y = pdfSimpleTable(doc, y, pageW, ['CLIENT', 'REQUESTED BY', 'AGE (DAYS)'], overdue.map((r) => [r.clientName, r.requestedByName, String(r.ageDays)]), [0.4, 0.35, 0.25]);
  }

  return finish(doc, h.companyName);
}

// 3. Missing-information report -- every pending request whose lead's KYC
// is incomplete (the same real deterministic check §9 capability 1's AI
// summary and the generator's own guard both use).
export function buildMissingInformationReport(requests: ContractRequest[], leadsById: Map<string, Lead>, h: ReportHeaderInput): jsPDF {
  const { doc, y: y0, pageW } = newReportDoc('MISSING-INFORMATION REPORT', `Pending requests with incomplete KYC, as of ${fmtLongDate(today())}`, h);
  let y = y0;

  const pending = requests.filter((r) => r.status === 'pending');
  const withGaps = pending
    .map((r) => ({ request: r, missing: missingKycFieldLabels(leadsById.get(r.leadId)) }))
    .filter((x) => x.missing.length > 0);
  const pct = pending.length ? Math.round((withGaps.length / pending.length) * 100) : 0;

  y = pdfSectionTitle(doc, y, pageW, 'Summary');
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'Pending requests', value: pending.length },
    { label: 'With incomplete KYC', value: withGaps.length, accent: withGaps.length ? PDF_DANGER : PDF_OK },
    { label: '% of pending blocked', value: `${pct}%`, accent: pct > 0 ? PDF_WARN : PDF_OK },
  ]);

  y = pdfSectionTitle(doc, y, pageW, 'Requests missing KYC data');
  if (withGaps.length) {
    y = pdfSimpleTable(doc, y, pageW, ['CLIENT', 'REQUESTED BY', 'MISSING FIELDS'], withGaps.map((x) => [x.request.clientName, x.request.requestedByName, x.missing.join(', ')]), [0.3, 0.25, 0.45]);
  } else {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(120, 130, 145);
    doc.text('Every pending request has complete KYC on file.', 14, y);
    doc.setTextColor(20, 20, 20);
  }

  return finish(doc, h.companyName);
}

// 4. Template-version usage report -- which published template versions
// have actually been used to generate a real contract (contract_
// generations.template_id/version_number_snapshot, the real audit-
// lineage fields set at generation time, §8).
export function buildTemplateUsageReport(generations: ContractGeneration[], templates: ContractTemplate[], h: ReportHeaderInput): jsPDF {
  const { doc, y: y0, pageW } = newReportDoc('TEMPLATE-VERSION USAGE REPORT', `All-time, as of ${fmtLongDate(today())}`, h);
  let y = y0;

  const templateName = (id: string | null) => templates.find((t) => t.id === id)?.name ?? 'Unknown template';
  type Usage = { key: string; name: string; version: number | null; count: number; lastUsed: string };
  const byKey = new Map<string, Usage>();
  for (const g of generations) {
    const key = `${g.templateId ?? 'none'}:${g.versionNumberSnapshot ?? 0}`;
    const existing = byKey.get(key);
    if (existing) {
      existing.count += 1;
      if (g.generatedAt > existing.lastUsed) existing.lastUsed = g.generatedAt;
    } else {
      byKey.set(key, { key, name: templateName(g.templateId), version: g.versionNumberSnapshot, count: 1, lastUsed: g.generatedAt });
    }
  }
  const usage = [...byKey.values()].sort((a, b) => b.count - a.count);

  y = pdfSectionTitle(doc, y, pageW, 'Summary');
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'Templates used at least once', value: new Set(usage.map((u) => u.name)).size },
    { label: 'Template-based generations', value: generations.length, accent: PDF_OK },
    { label: 'Most-used version', value: usage[0] ? `${usage[0].name} v${usage[0].version}` : '—' },
  ]);

  if (usage.length) {
    y = pdfSectionTitle(doc, y, pageW, 'Usage by version');
    y = pdfBarChart(
      doc,
      12,
      y,
      pageW - 24,
      38,
      usage.slice(0, 8).map((u, i) => ({ label: `${u.name} v${u.version}`, value: u.count, color: PDF_PALETTE[i % PDF_PALETTE.length] }))
    );
  }

  y = pdfSectionTitle(doc, y, pageW, 'Detail');
  if (usage.length) {
    y = pdfSimpleTable(doc, y, pageW, ['TEMPLATE', 'VERSION', 'TIMES USED', 'LAST USED'], usage.map((u) => [u.name, `v${u.version}`, String(u.count), u.lastUsed.slice(0, 10)]), [0.4, 0.15, 0.2, 0.25]);
  } else {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(120, 130, 145);
    doc.text('No template has been used to generate a contract yet.', 14, y);
    doc.setTextColor(20, 20, 20);
  }

  return finish(doc, h.companyName);
}

// 5. Turnaround-time report -- real days elapsed from contract_requests.
// created_at to fulfilled_at, for every actually-fulfilled request.
export function buildTurnaroundReport(requests: ContractRequest[], h: ReportHeaderInput): jsPDF {
  const { doc, y: y0, pageW } = newReportDoc('TURNAROUND-TIME REPORT', `Fulfilled requests, as of ${fmtLongDate(today())}`, h);
  let y = y0;

  const fulfilled = requests
    .filter((r) => r.status === 'fulfilled' && r.fulfilledAt)
    .map((r) => ({ ...r, days: daysBetween(r.createdAt, r.fulfilledAt as string) }))
    .sort((a, b) => b.days - a.days);
  const avg = fulfilled.length ? Math.round(fulfilled.reduce((s, r) => s + r.days, 0) / fulfilled.length) : 0;
  const fastest = fulfilled.length ? Math.min(...fulfilled.map((r) => r.days)) : 0;
  const slowest = fulfilled.length ? Math.max(...fulfilled.map((r) => r.days)) : 0;

  y = pdfSectionTitle(doc, y, pageW, 'Summary');
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'Fulfilled requests', value: fulfilled.length },
    { label: 'Average turnaround (days)', value: avg, accent: avg > 5 ? PDF_WARN : PDF_OK },
    { label: 'Fastest (days)', value: fastest, accent: PDF_OK },
    { label: 'Slowest (days)', value: slowest, accent: slowest > 5 ? PDF_DANGER : undefined },
  ]);

  y = pdfSectionTitle(doc, y, pageW, 'Fulfilled requests', 'slowest first');
  if (fulfilled.length) {
    y = pdfSimpleTable(
      doc,
      y,
      pageW,
      ['CLIENT', 'REQUESTED', 'FULFILLED', 'DAYS'],
      fulfilled.map((r) => [r.clientName, r.createdAt.slice(0, 10), (r.fulfilledAt as string).slice(0, 10), String(r.days)]),
      [0.35, 0.25, 0.25, 0.15]
    );
  } else {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(120, 130, 145);
    doc.text('No request has been fulfilled yet.', 14, y);
    doc.setTextColor(20, 20, 20);
  }

  const slow = fulfilled.filter((r) => r.days > 5);
  if (slow.length) {
    y = pdfSectionTitle(doc, y, pageW, 'Exceptions', `${slow.length} took more than 5 days`);
    y = pdfSimpleTable(doc, y, pageW, ['CLIENT', 'DAYS'], slow.map((r) => [r.clientName, String(r.days)]), [0.7, 0.3]);
  }

  return finish(doc, h.companyName);
}

// 6. Document status report -- Palmstead has no e-signature product yet,
// so there is no real "signed" boolean anywhere in the schema. Rather
// than invent one, this reports the closest genuine proxy: whether a
// request has actually had a document generated for it (contracts.list()
// -- the same real table that gets a row for every generation, template-
// based or legacy) crossed with its real fulfilled status. Labeled
// honestly rather than silently passing this off as signature tracking.
export function buildDocumentStatusReport(requests: ContractRequest[], contracts: Contract[], h: ReportHeaderInput): jsPDF {
  const { doc, y: y0, pageW } = newReportDoc('DOCUMENT STATUS REPORT', `As of ${fmtLongDate(today())} -- see note below`, h);
  let y = y0;

  const generatedLeadIds = new Set(contracts.map((c) => c.leadId));
  type Bucket = 'fulfilledWithDoc' | 'fulfilledNoDoc' | 'pendingWithDoc' | 'pendingNoDoc';
  const bucketed: Record<Bucket, ContractRequest[]> = { fulfilledWithDoc: [], fulfilledNoDoc: [], pendingWithDoc: [], pendingNoDoc: [] };
  for (const r of requests) {
    const hasDoc = generatedLeadIds.has(r.leadId);
    const key: Bucket = r.status === 'fulfilled' ? (hasDoc ? 'fulfilledWithDoc' : 'fulfilledNoDoc') : hasDoc ? 'pendingWithDoc' : 'pendingNoDoc';
    bucketed[key].push(r);
  }

  y = pdfSectionTitle(doc, y, pageW, 'Summary');
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'Fulfilled, document on file', value: bucketed.fulfilledWithDoc.length, accent: PDF_OK },
    { label: 'Fulfilled, no document', value: bucketed.fulfilledNoDoc.length, accent: bucketed.fulfilledNoDoc.length ? PDF_WARN : undefined },
    { label: 'Pending, document ready', value: bucketed.pendingWithDoc.length },
    { label: 'Pending, not generated', value: bucketed.pendingNoDoc.length },
  ]);

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(120, 130, 145);
  doc.text('Note: Palmstead does not yet track e-signature status. "Document on file" means a Contract of Sale PDF has been generated for this client at least once, not that it has been signed.', 14, y, { maxWidth: pageW - 28 });
  doc.setTextColor(20, 20, 20);
  y += 12;

  const rows: [string, ContractRequest[]][] = [
    ['Fulfilled, no document generated', bucketed.fulfilledNoDoc],
    ['Pending, not yet generated', bucketed.pendingNoDoc],
  ];
  for (const [label, list] of rows) {
    if (!list.length) continue;
    y = pdfSectionTitle(doc, y, pageW, label, `${list.length} request(s)`);
    y = pdfSimpleTable(doc, y, pageW, ['CLIENT', 'REQUESTED BY', 'REQUESTED'], list.map((r) => [r.clientName, r.requestedByName, r.createdAt.slice(0, 10)]), [0.4, 0.35, 0.25]);
  }

  return finish(doc, h.companyName);
}

export function contractReportFilename(kind: string): string {
  return `Contract_of_Sale_${kind}_${today()}.pdf`;
}
