"use client";

import { jsPDF } from 'jspdf';
import { pdfAccentStatRow, pdfBrandedHeader, pdfFitText, pdfGeneratedStamp, pdfReportFooter, pdfSectionTitle, PDF_LEAF, PDF_MUTED, PDF_OK, PDF_WARN, PDF_DANGER } from '../../../shared/lib/pdfReport';
import { BANNER_STATUS } from './bannerLogic';
import type { Banner, BannerStatusLogEntry } from '../../../types/domain';

function hexToRgb(hex: string): [number, number, number] {
  return [parseInt(hex.slice(1, 3), 16), parseInt(hex.slice(3, 5), 16), parseInt(hex.slice(5, 7), 16)];
}

// Exact port of the real production buildBannerReportPDF() -- one card
// per banner: its current photo (only a real on-file data-URI image,
// never fetched/invented), status pill, and its full status-update
// history (up to 5 most recent, "+N earlier updates not shown" beyond
// that) -- replacing the earlier flat NAME/STATUS/DATE table an earlier
// pass here ported from v1's OLDER, simpler report instead.
export function buildBannerReportPdf(banners: Banner[], logs: BannerStatusLogEntry[][], logoDataUri: string | null, generatedByName?: string | null): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  let y = pdfBrandedHeader(doc, 'BANNER TRACKING REPORT', 'Royal Palm Enclave, Tsopoli', [`Generated by ${generatedByName || ''}`, new Date().toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })], logoDataUri);
  y += 6;

  const placed = banners.filter((b) => b.status === 'placed').length;
  const maint = banners.filter((b) => b.status === 'needs_maintenance').length;
  const newLoc = banners.filter((b) => b.status === 'location_only').length;
  const replacing = banners.filter((b) => b.status === 'being_replaced').length;
  const areas = new Set(banners.map((b) => b.area).filter(Boolean));

  y = pdfSectionTitle(doc, y, pageW, 'Summary');
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'Banners in this report', value: banners.length, accent: PDF_LEAF },
    { label: 'Perfect condition', value: placed, accent: PDF_OK },
    { label: 'Needs maintenance', value: maint, accent: maint ? PDF_WARN : PDF_OK },
    { label: 'Being replaced', value: replacing, accent: replacing ? PDF_DANGER : PDF_OK },
    { label: 'Areas covered', value: areas.size, accent: PDF_LEAF },
  ]);
  y += 2;

  y = pdfSectionTitle(doc, y, pageW, 'Banners', `${banners.length} of ${banners.length} total`);
  if (!banners.length) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text('No banners match the selected filters.', 14, y);
    doc.setTextColor(20, 20, 20);
    y += 10;
  }

  banners.forEach((b, i) => {
    const log = logs[i] || [];
    const imgSize = 24;
    const historyLines = Math.min(log.length, 5) * 8 + (log.length > 5 ? 5 : 0);
    const blockH = Math.max(imgSize, 18) + historyLines + 14;
    if (y + blockH > 270) {
      doc.addPage();
      y = 20;
    }
    const status = BANNER_STATUS[b.status] || BANNER_STATUS.placed;
    let hasImg = false;
    if (b.image && /^data:image\//.test(b.image)) {
      try {
        doc.addImage(b.image, 'JPEG', 14, y, imgSize, imgSize);
        hasImg = true;
      } catch {
        // A malformed/undecodable photo shouldn't block the rest of the report.
      }
    }
    if (!hasImg) {
      doc.setFillColor(240, 242, 245);
      doc.roundedRect(14, y, imgSize, imgSize, 2, 2, 'F');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.5);
      doc.setTextColor(...PDF_MUTED);
      doc.text('No photo', 14 + imgSize / 2, y + imgSize / 2 + 1.5, { align: 'center' });
    }
    const tx = 14 + imgSize + 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10.5);
    doc.setTextColor(11, 30, 61);
    doc.text(pdfFitText(doc, b.name, 120), tx, y + 5);
    doc.setFillColor(...hexToRgb(status.color));
    doc.roundedRect(tx, y + 8, doc.getTextWidth(status.label) + 6, 5.5, 2, 2, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(255, 255, 255);
    doc.text(status.label, tx + 3, y + 11.7);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...PDF_MUTED);
    doc.text(pdfFitText(doc, `${b.area || '—'} · added by ${b.createdByName || '—'} on ${(b.createdAt || '').slice(0, 10)}`, 150), tx, y + 17);
    y += Math.max(imgSize, 20) + 3;

    if (log.length) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(...PDF_MUTED);
      doc.text('STATUS HISTORY', 14, y);
      y += 4.5;
      log.slice(0, 5).forEach((entry) => {
        const st = BANNER_STATUS[entry.status] || BANNER_STATUS.placed;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7.8);
        doc.setTextColor(20, 20, 20);
        doc.text(`${(entry.createdAt || '').slice(0, 10)}  ·  ${st.label}${entry.images && entry.images.length ? `  (${entry.images.length} photo${entry.images.length === 1 ? '' : 's'})` : ''}`, 14, y);
        y += 4;
        if (entry.note) {
          doc.setFont('helvetica', 'italic');
          doc.setFontSize(7.5);
          doc.setTextColor(...PDF_MUTED);
          const lines = doc.splitTextToSize(entry.note, pageW - 32);
          doc.text(lines, 14, y);
          y += lines.length * 3.6;
          doc.setTextColor(20, 20, 20);
        }
        y += 1.5;
      });
      if (log.length > 5) {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(7);
        doc.setTextColor(...PDF_MUTED);
        doc.text(`+${log.length - 5} earlier update${log.length - 5 === 1 ? '' : 's'} not shown`, 14, y);
        doc.setTextColor(20, 20, 20);
        y += 4;
      }
    } else {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(7.5);
      doc.setTextColor(...PDF_MUTED);
      doc.text('No status updates logged yet.', 14, y);
      doc.setTextColor(20, 20, 20);
      y += 4;
    }
    doc.setDrawColor(226, 231, 237);
    doc.setLineWidth(0.3);
    doc.line(14, y + 2, pageW - 14, y + 2);
    y += 7;
  });

  pdfReportFooter(doc, 'PEP Landbank');
  pdfGeneratedStamp(doc, generatedByName);
  return doc;
}

export function bannerReportFilename(): string {
  return `Banner_Tracking_Report_${new Date().toISOString().slice(0, 10)}.pdf`;
}
