import { jsPDF } from 'jspdf';
import { pdfAccentStatRow, pdfBarChart, pdfBrandedHeader, pdfReportFooter, pdfSectionTitle, pdfSimpleTable, PDF_DANGER, PDF_OK, PDF_PALETTE, PDF_WARN } from '../../../shared/lib/pdfReport';
import { fmtLongDate } from '../../../shared/lib/format';
import type { StaffAttendanceSummary } from './attendanceRecordsLogic';

// New 2026-09-10, user correction: "...or even pull a report on
// attendance." Same branded-report toolkit + page shape (KPI strip, bar
// chart, detailed table) every other company report in this app already
// uses (staffReportPdf.ts, commissionReportPdf.ts) -- matches the V3
// spec's own report blueprint too (executive cover+KPI, trend chart,
// detailed table, exceptions).
export function buildAttendanceRecordsPdf(summaries: StaffAttendanceSummary[], startDate: string, endDate: string, generatedByName: string, companyName: string | null | undefined, logoDataUri: string | null): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const rightLines = [`Generated by ${generatedByName}`, new Date().toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })];
  let y = pdfBrandedHeader(doc, 'ATTENDANCE RECORDS', `${fmtLongDate(startDate)} to ${fmtLongDate(endDate)}`, rightLines, logoDataUri);
  y += 6;

  const totalWorkDays = summaries[0]?.workDays ?? 0;
  const totalPresent = summaries.reduce((s, r) => s + r.present, 0);
  const totalLate = summaries.reduce((s, r) => s + r.late, 0);
  const totalAbsent = summaries.reduce((s, r) => s + r.absent, 0);
  const avgOnTimeRate = summaries.length ? Math.round(summaries.reduce((s, r) => s + r.onTimeRate, 0) / summaries.length) : 0;

  y = pdfSectionTitle(doc, y, pageW, 'Company-wide summary', `${totalWorkDays} work day(s) in range`);
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'Total present', value: totalPresent, accent: PDF_OK },
    { label: 'Total late', value: totalLate, accent: PDF_WARN },
    { label: 'Total absent', value: totalAbsent, accent: PDF_DANGER },
    { label: 'Avg on-time rate', value: `${avgOnTimeRate}%`, accent: PDF_OK },
  ]);

  if (summaries.length) {
    y = pdfSectionTitle(doc, y, pageW, 'On-time rate by staff');
    y = pdfBarChart(
      doc,
      12,
      y,
      pageW - 24,
      38,
      summaries.map((s, i) => ({ label: s.staffName, value: s.onTimeRate, color: PDF_PALETTE[i % PDF_PALETTE.length] }))
    );
  }

  y = pdfSectionTitle(doc, y, pageW, 'Detailed comparison', `${summaries.length} staff`);
  y = pdfSimpleTable(
    doc,
    y,
    pageW,
    ['STAFF', 'PRESENT', 'LATE', 'ABSENT', 'ON LEAVE', 'OFF-SITE', 'ON-TIME %'],
    summaries.map((s) => [s.staffName, String(s.present), String(s.late), String(s.absent), String(s.onLeave), String(s.offSite), `${s.onTimeRate}%`]),
    [0.28, 0.12, 0.1, 0.12, 0.12, 0.12, 0.14]
  );

  const exceptions = summaries.filter((s) => s.absent > 0 || s.onTimeRate < 80);
  if (exceptions.length) {
    if (y > 240) {
      doc.addPage();
      y = 16;
    }
    y = pdfSectionTitle(doc, y, pageW, 'Exceptions & attention', `${exceptions.length} staff below 80% on-time or with absences`);
    y = pdfSimpleTable(
      doc,
      y,
      pageW,
      ['STAFF', 'ABSENT', 'ON-TIME %'],
      exceptions.map((s) => [s.staffName, String(s.absent), `${s.onTimeRate}%`]),
      [0.5, 0.25, 0.25]
    );
  }

  pdfReportFooter(doc, companyName);
  return doc;
}

export function attendanceRecordsFilename(startDate: string, endDate: string): string {
  return `Attendance_Records_${startDate}_to_${endDate}.pdf`;
}
