import { jsPDF } from "jspdf";

import { loadImageAsDataUri } from "@/webnext/shared/lib/image";
import { pdfStampSignature } from "@/webnext/shared/lib/pdfSignature";
import { pdfBrandedHeader, pdfGeneratedStamp, pdfLedgerSection, pdfReportFooter, pdfSectionTitle, type PdfLedgerLine, PDF_INK, PDF_MUTED } from "@/webnext/shared/lib/pdfReport";

import type { CommissionReportConfig } from "./use-finance-commission";
import type { CalcEntry, CalcSettings } from "./use-commission-calculator";

// Real Commission Calculator PDF (Part E.2 -- the real user-corrected
// workflow). Deliberately DOES include each staff member's own bank
// account number, unlike a plain payroll register (real industry
// practice keeps that out of a register for security -- see this plan's
// own Part E.1 research) -- because this document's entire purpose IS
// the bank transfer instruction itself, the same real reasoning Payroll's
// own combined run PDF already uses.
function money(n: number): string {
  return `GHS ${n.toLocaleString("en-GH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function monthLabel(period: string): string {
  return new Date(`${period}-01T00:00:00`).toLocaleDateString("en-GB", { month: "long", year: "numeric" });
}

async function loadLogo(uploaded: string | null): Promise<string | null> {
  if (uploaded) return uploaded;
  try {
    return await loadImageAsDataUri("/trulander-logo.png");
  } catch {
    return null;
  }
}

export interface CalcPdfRow {
  payrollStaffId: string;
  staffName: string;
  bankAccountNumber: string | null;
  entries: CalcEntry[];
  personal: number;
  poolShare: number;
  eligible: boolean;
  total: number;
}

export async function buildCommissionCalculatorPdf(
  period: string,
  sessionName: string | null,
  settings: CalcSettings,
  rows: CalcPdfRow[],
  poolTotal: number,
  config: CommissionReportConfig,
  issuerSignature: string | null | undefined,
  issuerName: string | null | undefined,
): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const logo = await loadLogo(config.logoImage);
  let y = pdfBrandedHeader(
    doc,
    "COMMISSION CALCULATION",
    `${sessionName ? `${sessionName} — ` : ""}${monthLabel(period)}`,
    [`Generated by ${issuerName ?? "Management"}`, new Date().toLocaleDateString("en-GB")],
    logo,
  );
  y += 6;

  y = pdfSectionTitle(doc, y, pageW, "Settings used for this calculation");
  const settingsLines: PdfLedgerLine[] = [
    { label: "Full plot commission cap", value: money(settings.fullCap) },
    { label: "Half plot commission cap", value: money(settings.halfCap) },
    { label: "Full plot price", value: money(settings.fullPrice) },
    { label: "Half plot price", value: money(settings.halfPrice) },
    { label: "Pool amount per plot", value: money(settings.poolPerPlot) },
  ];
  y = pdfLedgerSection(doc, y, pageW, "Rates", settingsLines, "Pool total this month", money(poolTotal));

  y = pdfSectionTitle(doc, y, pageW, "By staff");
  for (const row of rows) {
    if (y > pageH - 40) {
      doc.addPage();
      y = 16;
    }
    const lines: PdfLedgerLine[] = row.entries.map((e) => ({
      label: `${e.clientName} — ${e.plotType}${e.isNewSale ? ` (new sale, ${e.noPlots} plot(s))` : ""}`,
      value: money(e.amount),
    }));
    lines.push({ label: "Personal commission", value: money(row.personal) });
    lines.push({ label: row.eligible ? "Pool share (eligible)" : "Pool share (not eligible)", value: money(row.poolShare) });
    y = pdfLedgerSection(doc, y, pageW, row.staffName, lines, `Total — ${row.staffName}`, money(row.total));
  }

  const grandTotal = rows.reduce((s, r) => s + r.total, 0);
  if (y > pageH - 90) {
    doc.addPage();
    y = 16;
  }
  y = pdfSectionTitle(doc, y, pageW, "Paying account");
  const bankRows: PdfLedgerLine[] = [
    { label: "Bank", value: config.bankName || "—" },
    { label: "Account name", value: config.bankAccountName || "—" },
    { label: "Account number", value: config.bankAccountNumber || "—" },
  ];
  bankRows.forEach((row, i) => {
    const ry = y + i * 6.5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...PDF_MUTED);
    doc.text(row.label.toUpperCase(), 12, ry);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...PDF_INK);
    doc.text(row.value, 54, ry);
  });
  y += bankRows.length * 6.5 + 4;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...PDF_INK);
  doc.text(`TOTAL PAYABLE: ${money(grandTotal)}`, pageW - 12, y, { align: "right" });
  y += 10;

  y = pdfSectionTitle(doc, y, pageW, "Transfer instructions");
  y = pdfLedgerSection(
    doc,
    y,
    pageW,
    "Staff accounts",
    rows.map((r) => ({ label: `${r.staffName} — acct ${r.bankAccountNumber || "not on file"}`, value: money(r.total) })),
    "Total payable",
    money(grandTotal),
    { emphasize: true },
  );

  if (y > pageH - 40) {
    doc.addPage();
    y = 16;
  }
  if (issuerSignature) pdfStampSignature(doc, 12, y - 2, 45, 16, issuerSignature);
  doc.setDrawColor(201, 162, 39);
  doc.setLineWidth(0.6);
  doc.line(12, y, 12 + 65, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...PDF_MUTED);
  doc.text("Authorized Signature — Management", 12, y);
  doc.text(issuerName ?? "", 12, y + 5);

  pdfReportFooter(doc, config.companyName);
  pdfGeneratedStamp(doc, issuerName);
  return doc;
}
