"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, ChevronLeft, ChevronRight, Download } from "lucide-react";
import { jsPDF } from "jspdf";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import { SubmitButton } from "@/components/submit-button";
import { Textarea } from "@/components/ui/textarea";
import { shiftMonth, today } from "@/lib/palmstead/format";
import { loadImageAsDataUri } from "@/webnext/shared/lib/image";
import { pdfStampSignature } from "@/webnext/shared/lib/pdfSignature";
import { pdfAccentStatRow, pdfBarChart, pdfBrandedHeader, pdfGeneratedStamp, pdfReportFooter, pdfSectionTitle, pdfSimpleTable, PDF_GOLD, PDF_INK, PDF_LEAF, PDF_MUTED, PDF_OK, PDF_PALETTE } from "@/webnext/shared/lib/pdfReport";
import { useAuthStore } from "@/stores/auth/auth-store";

import { type CommissionReportConfig, type CommissionRow, useCommissionBreakdown, useCommissionReportConfig, useRaiseCommissionConcern } from "./use-finance-commission";

// Real Commission (Part B.4). No new math -- get_commission_breakdown()
// is a direct extraction of run_monthly_commission_check()'s own real
// formula, verified byte-for-byte against the original inline version
// when it was built (see this plan's own A.2 section). Manager defaults
// to last month (the real payable month, matching V1's own
// mgrCommission()); a non-manager's own row always comes back scoped by
// the RPC itself.
function money(n: number): string {
  return `GHS ${n.toLocaleString("en-GH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function monthLabel(mk: string): string {
  return new Date(`${mk}-01T00:00:00`).toLocaleDateString("en-GB", { month: "long", year: "numeric" });
}

async function loadReportLogo(): Promise<string | null> {
  try {
    return await loadImageAsDataUri("/trulander-logo.png");
  } catch {
    // Missing/blocked logo shouldn't stop the report from generating.
    return null;
  }
}

async function buildCommissionReportPdf(
  month: string,
  rows: CommissionRow[],
  generatedByName: string | null | undefined,
  config: CommissionReportConfig,
  issuerSignature: string | null | undefined,
): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const payable = `${shiftMonth(month, 1)}-15`;
  const logo = await loadReportLogo();
  let y = pdfBrandedHeader(doc, "COMMISSION REPORT", `${monthLabel(month)}  ·  payable ${payable}`, [`Generated by ${generatedByName ?? "Management"}`, new Date().toLocaleDateString("en-GB")], logo);
  y += 6;

  const poolTotal = rows[0]?.poolTotal ?? 0;
  const eligibleCount = rows[0]?.eligibleCount ?? 0;
  const grandTotal = rows.reduce((s, r) => s + r.total, 0);
  y = pdfSectionTitle(doc, y, pageW, "Pool summary");
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: "Pool total", value: money(poolTotal), accent: PDF_GOLD },
    { label: "Eligible agents", value: eligibleCount, accent: PDF_LEAF },
    { label: "Total payable", value: money(grandTotal), accent: PDF_OK },
  ]);

  if (rows.length) {
    y = pdfSectionTitle(doc, y, pageW, "By agent — earnings breakdown");
    y = pdfBarChart(
      doc,
      12,
      y,
      pageW - 24,
      38,
      rows
        .slice()
        .sort((a, b) => b.total - a.total)
        .slice(0, 8)
        .map((r, i) => ({ label: r.agentName, value: Math.round(r.total), color: PDF_PALETTE[i % PDF_PALETTE.length] })),
    );
  }
  y = pdfSectionTitle(doc, y, pageW, "By agent — detail");
  y = pdfSimpleTable(
    doc,
    y,
    pageW,
    ["AGENT", "PERSONAL", "POOL", "TOTAL"],
    rows.map((r) => [r.agentName, money(r.personal), r.isPoolEligible ? money(r.poolShare) : "—", money(r.total)]),
    [0.4, 0.2, 0.2, 0.2],
  );

  // Payment sign-off -- real company bank-account details plus a real
  // signature line, so this report can go straight to the bank for
  // payment once Management signs off, per the user's own explicit ask.
  // Blank bank fields show "—" rather than blocking the report; fill them
  // in via Finance Settings (docs/plans/04-finance-app-plan.md Part B.7).
  if (y > pageH - 70) {
    doc.addPage();
    y = 16;
  }
  y += 4;
  y = pdfSectionTitle(doc, y, pageW, "Payment sign-off");
  const bankL = 12;
  const bankColW = (pageW - 24) / 2;
  const bankRows: [string, string][] = [
    ["Bank", config.bankName || "—"],
    ["Account name", config.bankAccountName || "—"],
    ["Account number", config.bankAccountNumber || "—"],
    ["Branch", config.bankBranch || "—"],
    ["SWIFT/sort code", config.bankSwiftCode || "—"],
  ];
  const bankRowH = 7;
  bankRows.forEach((row, i) => {
    const ry = y + i * bankRowH;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...PDF_MUTED);
    doc.text(row[0].toUpperCase(), bankL, ry);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...PDF_INK);
    doc.text(row[1], bankL + 42, ry);
  });

  const sigX = bankL + bankColW + 12;
  const sigY = y + bankRows.length * bankRowH - 8;
  if (issuerSignature) pdfStampSignature(doc, sigX, sigY - 14, 45, 16, issuerSignature);
  doc.setDrawColor(...PDF_GOLD);
  doc.setLineWidth(0.6);
  doc.line(sigX, sigY, sigX + 65, sigY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...PDF_MUTED);
  doc.text("Authorized Signature — Management", sigX, sigY + 5);
  doc.text(generatedByName ?? "", sigX, sigY + 10);

  pdfReportFooter(doc, config.companyName);
  pdfGeneratedStamp(doc, generatedByName);
  return doc;
}

function ConcernDialog({ month, total, callerKey, callerName }: { month: string; total: number; callerKey: string | undefined; callerName: string | undefined }) {
  const [open, setOpen] = useState(false);
  const [note, setNote] = useState("");
  const raise = useRaiseCommissionConcern(callerKey, callerName);

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="w-full">
          <AlertTriangle data-icon="inline-start" />
          This doesn't look right — raise a concern
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-sm">
        <DialogHeader>
          <DialogTitle>Raise a commission concern</DialogTitle>
        </DialogHeader>
        <p className="text-sm text-muted-foreground">
          Sends Management a message with your {monthLabel(month)} total ({money(total)}) so they can look into it.
        </p>
        <Textarea placeholder="e.g. a payment is missing, or the amount for a client looks off…" value={note} onChange={(e) => setNote(e.target.value)} rows={3} />
        <DialogFooter>
          <SubmitButton
            loading={raise.isPending}
            disabled={!note.trim()}
            onClick={async () => {
              await raise.mutateAsync({ month, total, note: note.trim() });
              setNote("");
              setOpen(false);
            }}
          >
            Send to Management
          </SubmitButton>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export function CommissionPanel() {
  const profile = useAuthStore((s) => s.profile);
  const isManager = profile?.role === "manager";
  const [cursor, setCursor] = useState(() => shiftMonth(today().slice(0, 7), -1));
  const { data: rows, isLoading } = useCommissionBreakdown(cursor);
  const { data: reportConfig } = useCommissionReportConfig();
  const [downloading, setDownloading] = useState(false);

  const sorted = useMemo(() => (rows ?? []).slice().sort((a, b) => b.total - a.total), [rows]);
  const myRow = rows?.find((r) => r.agentKey === profile?.key);
  const poolTotal = rows?.[0]?.poolTotal ?? 0;
  const eligibleCount = rows?.[0]?.eligibleCount ?? 0;
  const grandTotal = (rows ?? []).reduce((s, r) => s + r.total, 0);

  if (isLoading) {
    return (
      <div className="flex flex-col gap-3">
        <Skeleton className="h-16 w-full" />
        <Skeleton className="h-64 w-full" />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-medium">Commission</h2>
          <p className="text-sm text-muted-foreground">Personal + pool, paid on the 15th of the following month.</p>
        </div>
        {isManager && rows && rows.length > 0 && (
          <Button
            variant="outline"
            size="sm"
            disabled={downloading || !reportConfig}
            onClick={async () => {
              if (!reportConfig) return;
              setDownloading(true);
              try {
                const doc = await buildCommissionReportPdf(cursor, sorted, profile?.name, reportConfig, profile?.signatureData);
                doc.save(`Commission_${cursor}.pdf`);
              } finally {
                setDownloading(false);
              }
            }}
          >
            <Download data-icon="inline-start" />
            {downloading ? "Preparing…" : "Download report"}
          </Button>
        )}
      </div>

      <Card>
        <CardContent className="flex items-center gap-3 py-4">
          <Button variant="outline" size="icon-sm" onClick={() => setCursor((c) => shiftMonth(c, -1))}>
            <ChevronLeft />
          </Button>
          <div className="flex-1 text-center">
            <div className="font-medium">{monthLabel(cursor)}</div>
            <div className="text-muted-foreground text-xs">Payable {shiftMonth(cursor, 1)}-15</div>
          </div>
          <Button variant="outline" size="icon-sm" onClick={() => setCursor((c) => shiftMonth(c, 1))} disabled={cursor >= shiftMonth(today().slice(0, 7), -1)}>
            <ChevronRight />
          </Button>
        </CardContent>
      </Card>

      {isManager ? (
        <>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
            <Card>
              <CardHeader>
                <CardDescription>Pool total</CardDescription>
                <CardTitle className="text-2xl tabular-nums">{money(poolTotal)}</CardTitle>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <CardDescription>Eligible agents</CardDescription>
                <CardTitle className="text-2xl tabular-nums">{eligibleCount}</CardTitle>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <CardDescription>Total payable</CardDescription>
                <CardTitle className="text-2xl tabular-nums">{money(grandTotal)}</CardTitle>
              </CardHeader>
            </Card>
          </div>

          <Card>
            <CardHeader>
              <CardTitle className="text-base">By agent</CardTitle>
            </CardHeader>
            <CardContent className="flex flex-col gap-3">
              {sorted.length === 0 && <p className="py-6 text-center text-sm text-muted-foreground">No agents to show for this month.</p>}
              {sorted.map((r) => (
                <div key={r.agentKey} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border p-3">
                  <div className="font-medium">{r.agentName}</div>
                  <div className="flex items-center gap-2">
                    <Badge variant="outline">Personal {money(r.personal)}</Badge>
                    {r.isPoolEligible ? <Badge>Pool {money(r.poolShare)}</Badge> : <Badge variant="secondary">Pool: 3 months no sale</Badge>}
                    <span className="font-medium tabular-nums">{money(r.total)}</span>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </>
      ) : (
        <Card>
          <CardHeader>
            <CardDescription>Your {monthLabel(cursor)} commission</CardDescription>
            <CardTitle className="text-3xl tabular-nums">{money(myRow?.total ?? 0)}</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <div className="flex items-center gap-2">
              <Badge variant="outline">Personal {money(myRow?.personal ?? 0)}</Badge>
              {myRow?.isPoolEligible ? <Badge>Pool {money(myRow.poolShare)}</Badge> : <Badge variant="secondary">Pool: 3 months no sale</Badge>}
            </div>
            <ConcernDialog month={cursor} total={myRow?.total ?? 0} callerKey={profile?.key} callerName={profile?.name} />
          </CardContent>
        </Card>
      )}
    </div>
  );
}
