import { jsPDF } from "jspdf";

import { loadImageAsDataUri } from "@/webnext/shared/lib/image";
import { pdfStampSignature } from "@/webnext/shared/lib/pdfSignature";
import { pdfBrandedHeader, pdfGeneratedStamp, pdfReportFooter, pdfSectionTitle, pdfSimpleTable, PDF_INK, PDF_MUTED } from "@/webnext/shared/lib/pdfReport";

import type { CommissionReportConfig } from "./use-finance-commission";
import type { PayrollRunLine } from "./use-finance-payroll";

function money(n: number): string {
  return `GHS ${n.toLocaleString("en-GH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function monthLabel(mk: string): string {
  return new Date(`${mk}-01T00:00:00`).toLocaleDateString("en-GB", { month: "long", year: "numeric" });
}

async function loadLogo(uploadedLogo: string | null | undefined): Promise<string | null> {
  if (uploadedLogo) return uploadedLogo;
  try {
    return await loadImageAsDataUri("/trulander-logo.png");
  } catch {
    return null;
  }
}

function netPayFor(lines: PayrollRunLine[]): number {
  return lines.reduce((s, l) => s + (l.componentType === "earning" ? l.amount : -l.amount), 0);
}

// Per-employee payslip -- their own earnings/deductions breakdown and net
// pay, plus their own bank account shown for reference. Informational to
// the employee, no sign-off needed here (that's the combined run document).
export async function buildPayslipPdf(period: string, staffName: string, bankAccountNumber: string | null, lines: PayrollRunLine[], companyName: string, logoImage?: string | null): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoImage);
  let y = pdfBrandedHeader(doc, "PAYSLIP", `${staffName}  ·  ${monthLabel(period)}`, [companyName, new Date().toLocaleDateString("en-GB")], logo);
  y += 6;

  const earnings = lines.filter((l) => l.componentType === "earning");
  const deductions = lines.filter((l) => l.componentType === "deduction");
  const net = netPayFor(lines);

  y = pdfSectionTitle(doc, y, pageW, "Earnings");
  y = pdfSimpleTable(
    doc,
    y,
    pageW,
    ["COMPONENT", "AMOUNT"],
    earnings.length ? earnings.map((l) => [l.componentName, money(l.amount)]) : [["—", money(0)]],
    [0.7, 0.3],
  );

  y = pdfSectionTitle(doc, y, pageW, "Deductions");
  y = pdfSimpleTable(
    doc,
    y,
    pageW,
    ["COMPONENT", "AMOUNT"],
    deductions.length ? deductions.map((l) => [l.componentName, money(l.amount)]) : [["—", money(0)]],
    [0.7, 0.3],
  );

  y += 4;
  doc.setFillColor(...PDF_INK);
  doc.roundedRect(12, y, pageW - 24, 16, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text("NET PAY", 18, y + 10);
  doc.setFontSize(13);
  doc.text(money(net), pageW - 18, y + 10, { align: "right" });
  y += 24;

  if (bankAccountNumber) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...PDF_MUTED);
    doc.text(`Paid to account ending ${bankAccountNumber.slice(-4)}`, 12, y);
  }

  pdfReportFooter(doc, companyName);
  pdfGeneratedStamp(doc, companyName);
  return doc;
}

// The real document this is all for -- "send it to the bank to pay
// staff": company's own paying bank account, every payee's individual
// bank account and net-pay amount in one transfer-instruction table,
// total payable, and a real signature line for Management's sign-off.
export async function buildPayrollRunPdf(period: string, allLines: PayrollRunLine[], config: CommissionReportConfig, issuerSignature: string | null | undefined, issuerName: string | null | undefined, staffBankLookup: Map<string, string | null>): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const logo = await loadLogo(config.logoImage);
  let y = pdfBrandedHeader(doc, "PAYROLL RUN", `${monthLabel(period)}  ·  bank transfer instruction`, [`Generated by ${issuerName ?? "Management"}`, new Date().toLocaleDateString("en-GB")], logo);
  y += 6;

  y = pdfSectionTitle(doc, y, pageW, "Paying account");
  const payRows: [string, string][] = [
    ["Bank", config.bankName || "—"],
    ["Account name", config.bankAccountName || "—"],
    ["Account number", config.bankAccountNumber || "—"],
  ];
  payRows.forEach((row, i) => {
    const ry = y + i * 6.5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...PDF_MUTED);
    doc.text(row[0].toUpperCase(), 12, ry);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...PDF_INK);
    doc.text(row[1], 54, ry);
  });
  y += payRows.length * 6.5 + 6;

  const byStaff = new Map<string, { name: string; net: number }>();
  for (const l of allLines) {
    const existing = byStaff.get(l.payrollStaffId);
    const delta = l.componentType === "earning" ? l.amount : -l.amount;
    if (existing) existing.net += delta;
    else byStaff.set(l.payrollStaffId, { name: l.staffName, net: delta });
  }
  const rows = [...byStaff.entries()].map(([staffId, v]) => [v.name, staffBankLookup.get(staffId) || "—", money(v.net)]);
  const total = [...byStaff.values()].reduce((s, v) => s + v.net, 0);

  y = pdfSectionTitle(doc, y, pageW, "Transfer instructions");
  y = pdfSimpleTable(doc, y, pageW, ["STAFF", "ACCOUNT NUMBER", "NET PAY"], rows, [0.4, 0.35, 0.25]);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...PDF_INK);
  doc.text(`TOTAL PAYABLE: ${money(total)}`, pageW - 12, y, { align: "right" });
  y += 14;

  if (y > pageH - 40) {
    doc.addPage();
    y = 16;
  }
  if (issuerSignature) pdfStampSignature(doc, 12, y - 2, 45, 16, issuerSignature);
  doc.setDrawColor(201, 162, 39);
  doc.setLineWidth(0.6);
  doc.line(12, y, 12 + 65, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...PDF_MUTED);
  doc.text("Authorized Signature — Management", 12, y);
  doc.text(issuerName ?? "", 12, y + 5);

  pdfReportFooter(doc, config.companyName);
  pdfGeneratedStamp(doc, issuerName);
  return doc;
}
