import { jsPDF } from "jspdf";

import { loadImageAsDataUri } from "@/webnext/shared/lib/image";
import { pdfBrandedHeader, pdfGeneratedStamp, pdfLedgerSection, pdfReportFooter, pdfSectionTitle, type PdfLedgerLine } from "@/webnext/shared/lib/pdfReport";

import type { CommissionReportRow, DateRange, ExpensesReportRow, PaymentsReportRow, PayrollReportRow } from "./use-finance-reports";

// Real grouped-ledger report PDFs (Part B.10, rebuilt 2026-10-10 against
// Xero's own real published P&L sample -- see docs/plans/05-accounting-app-blueprint.md
// Part E.1). Every report here is a real statement-shaped document: a
// bold section header, every real row of detail (not collapsed into a
// handful of stat boxes), a shaded TOTAL row per section -- the same
// visual family pdfLedgerSection already gives every report in this app.
function money(n: number): string {
  return `GHS ${n.toLocaleString("en-GH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function fmtDate(d: string): string {
  return new Date(`${d}T00:00:00`).toLocaleDateString("en-GB");
}

async function loadLogo(uploaded: string | null): Promise<string | null> {
  if (uploaded) return uploaded;
  try {
    return await loadImageAsDataUri("/trulander-logo.png");
  } catch {
    return null;
  }
}

function header(doc: jsPDF, title: string, range: DateRange, companyName: string, generatedBy: string | null | undefined, logo: string | null): number {
  let y = pdfBrandedHeader(doc, title.toUpperCase(), `${fmtDate(range.start)} – ${fmtDate(range.end)}`, [companyName, `Generated by ${generatedBy ?? "Management"}`], logo);
  return y + 6;
}

function checkPageBreak(doc: jsPDF, y: number): number {
  if (y > 262) {
    doc.addPage();
    return 16;
  }
  return y;
}

export async function buildPaymentsReportPdf(range: DateRange, rows: PaymentsReportRow[], companyName: string, generatedBy: string | null | undefined, logoImage: string | null): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoImage);
  let y = header(doc, "Payments Report", range, companyName, generatedBy, logo);

  const approved = rows.filter((r) => r.status === "approved");
  const total = approved.reduce((s, r) => s + r.amount, 0);

  // Grouped by agent, matching a real receivables-by-salesperson breakdown
  // -- not a flat undifferentiated list.
  const byAgent = new Map<string, PaymentsReportRow[]>();
  for (const r of rows) {
    const list = byAgent.get(r.agentKey) ?? [];
    list.push(r);
    byAgent.set(r.agentKey, list);
  }

  y = pdfSectionTitle(doc, y, pageW, "Payments", `${rows.length} transaction(s), ${approved.length} approved`);
  for (const [agentKey, agentRows] of [...byAgent.entries()].sort((a, b) => b[1].length - a[1].length)) {
    y = checkPageBreak(doc, y);
    const agentApproved = agentRows.filter((r) => r.status === "approved");
    const lines: PdfLedgerLine[] = agentRows.map((r) => ({
      label: `${fmtDate(r.paymentDate)} — ${r.leadName} (${r.paymentMethod ?? "—"}, ${r.status})`,
      value: money(r.amount),
    }));
    y = pdfLedgerSection(doc, y, pageW, agentKey, lines, `Total — ${agentKey}`, money(agentApproved.reduce((s, r) => s + r.amount, 0)));
  }

  y = checkPageBreak(doc, y);
  y = pdfLedgerSection(doc, y, pageW, "Overall", [], "Total collected (approved)", money(total), { emphasize: true });

  pdfReportFooter(doc, companyName);
  pdfGeneratedStamp(doc, generatedBy);
  return doc;
}

export async function buildExpensesReportPdf(range: DateRange, rows: ExpensesReportRow[], companyName: string, generatedBy: string | null | undefined, logoImage: string | null): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoImage);
  let y = header(doc, "Expenses Report", range, companyName, generatedBy, logo);

  const approved = rows.filter((r) => r.status === "approved");
  const total = approved.reduce((s, r) => s + r.amount, 0);

  const byCategory = new Map<string, ExpensesReportRow[]>();
  for (const r of rows) {
    const list = byCategory.get(r.category) ?? [];
    list.push(r);
    byCategory.set(r.category, list);
  }

  y = pdfSectionTitle(doc, y, pageW, "Expenses by category", `${rows.length} entries, ${approved.length} approved`);
  for (const [category, catRows] of [...byCategory.entries()].sort((a, b) => b[1].length - a[1].length)) {
    y = checkPageBreak(doc, y);
    const catApproved = catRows.filter((r) => r.status === "approved");
    const lines: PdfLedgerLine[] = catRows.map((r) => ({
      label: `${fmtDate(r.expenseDate)} — ${r.loggedByName ?? "—"} (${r.paymentMethod}, ${r.status})`,
      value: money(r.amount),
    }));
    y = pdfLedgerSection(doc, y, pageW, category, lines, `Total — ${category}`, money(catApproved.reduce((s, r) => s + r.amount, 0)));
  }

  y = checkPageBreak(doc, y);
  y = pdfLedgerSection(doc, y, pageW, "Overall", [], "Total spend (approved)", money(total), { emphasize: true });

  pdfReportFooter(doc, companyName);
  pdfGeneratedStamp(doc, generatedBy);
  return doc;
}

export async function buildCommissionReportRangePdf(range: DateRange, rows: CommissionReportRow[], companyName: string, generatedBy: string | null | undefined, logoImage: string | null): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoImage);
  let y = header(doc, "Commission Report", range, companyName, generatedBy, logo);

  const total = rows.reduce((s, r) => s + r.total, 0);
  const byMonth = new Map<string, CommissionReportRow[]>();
  for (const r of rows) {
    const list = byMonth.get(r.month) ?? [];
    list.push(r);
    byMonth.set(r.month, list);
  }

  y = pdfSectionTitle(doc, y, pageW, "Commission by month", `${new Set(rows.map((r) => r.month)).size} month(s) covered`);
  for (const [month, monthRows] of [...byMonth.entries()].sort()) {
    y = checkPageBreak(doc, y);
    const lines: PdfLedgerLine[] = monthRows.map((r) => ({ label: `${r.agentName} — personal ${money(r.personal)} + pool ${money(r.poolShare)}`, value: money(r.total) }));
    y = pdfLedgerSection(doc, y, pageW, month, lines, `Total — ${month}`, money(monthRows.reduce((s, r) => s + r.total, 0)));
  }

  y = checkPageBreak(doc, y);
  y = pdfLedgerSection(doc, y, pageW, "Overall", [], "Total commission", money(total), { emphasize: true });

  pdfReportFooter(doc, companyName);
  pdfGeneratedStamp(doc, generatedBy);
  return doc;
}

export async function buildPayrollReportPdf(range: DateRange, rows: PayrollReportRow[], companyName: string, generatedBy: string | null | undefined, logoImage: string | null): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoImage);
  let y = header(doc, "Payroll Report", range, companyName, generatedBy, logo);

  const total = rows.reduce((s, r) => s + r.net, 0);
  const byPeriod = new Map<string, PayrollReportRow[]>();
  for (const r of rows) {
    const list = byPeriod.get(r.period) ?? [];
    list.push(r);
    byPeriod.set(r.period, list);
  }

  y = pdfSectionTitle(doc, y, pageW, "Payroll by period", `${new Set(rows.map((r) => r.period)).size} run(s)`);
  for (const [period, periodRows] of [...byPeriod.entries()].sort()) {
    y = checkPageBreak(doc, y);
    const lines: PdfLedgerLine[] = periodRows.map((r) => ({ label: `${r.staffName} (${r.status.replace("_", " ")})`, value: money(r.net) }));
    y = pdfLedgerSection(doc, y, pageW, period, lines, `Total — ${period}`, money(periodRows.reduce((s, r) => s + r.net, 0)));
  }

  y = checkPageBreak(doc, y);
  y = pdfLedgerSection(doc, y, pageW, "Overall", [], "Total net pay", money(total), { emphasize: true });

  pdfReportFooter(doc, companyName);
  pdfGeneratedStamp(doc, generatedBy);
  return doc;
}

// Real income-statement-shaped Financial Summary, matching Xero's own
// real P&L grouping (Revenue, then each outflow its own section, then a
// final emphasized Net row) -- not a row of stat boxes. Every section
// carries its real line items, not just a number.
export async function buildSummaryReportPdf(
  range: DateRange,
  payments: PaymentsReportRow[],
  expenses: ExpensesReportRow[],
  commission: CommissionReportRow[],
  payroll: PayrollReportRow[],
  companyName: string,
  generatedBy: string | null | undefined,
  logoImage: string | null,
): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoImage);
  let y = header(doc, "Financial Summary", range, companyName, generatedBy, logo);

  const approvedPayments = payments.filter((r) => r.status === "approved");
  const approvedExpenses = expenses.filter((r) => r.status === "approved");
  const collected = approvedPayments.reduce((s, r) => s + r.amount, 0);
  const expensesTotal = approvedExpenses.reduce((s, r) => s + r.amount, 0);
  const commissionTotal = commission.reduce((s, r) => s + r.total, 0);
  const payrollTotal = payroll.reduce((s, r) => s + r.net, 0);
  const net = collected - expensesTotal - commissionTotal - payrollTotal;

  y = pdfSectionTitle(doc, y, pageW, "Income statement");

  const revenueLines: PdfLedgerLine[] = approvedPayments.slice(0, 40).map((r) => ({ label: `${fmtDate(r.paymentDate)} — ${r.leadName}`, value: money(r.amount) }));
  if (approvedPayments.length > 40) revenueLines.push({ label: `…and ${approvedPayments.length - 40} more (see Payments report for full detail)`, value: "" });
  y = pdfLedgerSection(doc, y, pageW, "Revenue — collected payments", revenueLines, "Total revenue", money(collected));

  y = checkPageBreak(doc, y);
  const expenseByCategory = new Map<string, number>();
  for (const r of approvedExpenses) expenseByCategory.set(r.category, (expenseByCategory.get(r.category) ?? 0) + r.amount);
  const expenseLines: PdfLedgerLine[] = [...expenseByCategory.entries()].sort((a, b) => b[1] - a[1]).map(([c, a]) => ({ label: c, value: money(a) }));
  y = pdfLedgerSection(doc, y, pageW, "Expenses", expenseLines, "Total expenses", money(expensesTotal));

  y = checkPageBreak(doc, y);
  const commissionByAgent = new Map<string, number>();
  for (const r of commission) commissionByAgent.set(r.agentName, (commissionByAgent.get(r.agentName) ?? 0) + r.total);
  const commissionLines: PdfLedgerLine[] = [...commissionByAgent.entries()].sort((a, b) => b[1] - a[1]).map(([a, v]) => ({ label: a, value: money(v) }));
  y = pdfLedgerSection(doc, y, pageW, "Commission paid", commissionLines, "Total commission", money(commissionTotal));

  y = checkPageBreak(doc, y);
  const payrollByStaff = new Map<string, number>();
  for (const r of payroll) payrollByStaff.set(r.staffName, (payrollByStaff.get(r.staffName) ?? 0) + r.net);
  const payrollLines: PdfLedgerLine[] = [...payrollByStaff.entries()].sort((a, b) => b[1] - a[1]).map(([s, v]) => ({ label: s, value: money(v) }));
  y = pdfLedgerSection(doc, y, pageW, "Payroll paid", payrollLines, "Total payroll", money(payrollTotal));

  y = checkPageBreak(doc, y);
  y = pdfLedgerSection(doc, y, pageW, "Net", [], "Net (revenue − expenses − commission − payroll)", money(net), { emphasize: true });

  pdfReportFooter(doc, companyName);
  pdfGeneratedStamp(doc, generatedBy);
  return doc;
}
