import { jsPDF } from "jspdf";

import { loadImageAsDataUri } from "@/webnext/shared/lib/image";
import { pdfAccentStatRow, pdfBrandedHeader, pdfGeneratedStamp, pdfReportFooter, pdfSectionTitle, pdfSimpleTable, PDF_GOLD, PDF_LEAF, PDF_OK, PDF_WARN } from "@/webnext/shared/lib/pdfReport";

import type { CommissionReportRow, DateRange, ExpensesReportRow, PaymentsReportRow, PayrollReportRow } from "./use-finance-reports";

function money(n: number): string {
  return `GHS ${n.toLocaleString("en-GH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function fmtDate(d: string): string {
  return new Date(`${d}T00:00:00`).toLocaleDateString("en-GB");
}

async function loadLogo(uploaded: string | null): Promise<string | null> {
  if (uploaded) return uploaded;
  try {
    return await loadImageAsDataUri("/trulander-logo.png");
  } catch {
    return null;
  }
}

function header(doc: jsPDF, title: string, range: DateRange, companyName: string, generatedBy: string | null | undefined, logo: string | null): number {
  const pageW = doc.internal.pageSize.getWidth();
  let y = pdfBrandedHeader(doc, title.toUpperCase(), `${fmtDate(range.start)} – ${fmtDate(range.end)}`, [companyName, `Generated by ${generatedBy ?? "Management"}`], logo);
  return y + 6;
}

export async function buildPaymentsReportPdf(range: DateRange, rows: PaymentsReportRow[], companyName: string, generatedBy: string | null | undefined, logoImage: string | null): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoImage);
  let y = header(doc, "Payments Report", range, companyName, generatedBy, logo);

  const approved = rows.filter((r) => r.status === "approved");
  const total = approved.reduce((s, r) => s + r.amount, 0);
  y = pdfSectionTitle(doc, y, pageW, "Summary");
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: "Total collected", value: money(total), accent: PDF_OK },
    { label: "Approved payments", value: approved.length, accent: PDF_LEAF },
    { label: "All entries", value: rows.length, accent: PDF_GOLD },
  ]);

  y = pdfSectionTitle(doc, y, pageW, "Transactions");
  y = pdfSimpleTable(
    doc,
    y,
    pageW,
    ["DATE", "CLIENT", "AGENT", "METHOD", "STATUS", "AMOUNT"],
    rows.map((r) => [fmtDate(r.paymentDate), r.leadName, r.agentKey, r.paymentMethod ?? "—", r.status, money(r.amount)]),
    [0.15, 0.28, 0.15, 0.15, 0.12, 0.15],
  );

  pdfReportFooter(doc, companyName);
  pdfGeneratedStamp(doc, generatedBy);
  return doc;
}

export async function buildExpensesReportPdf(range: DateRange, rows: ExpensesReportRow[], companyName: string, generatedBy: string | null | undefined, logoImage: string | null): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoImage);
  let y = header(doc, "Expenses Report", range, companyName, generatedBy, logo);

  const approved = rows.filter((r) => r.status === "approved");
  const total = approved.reduce((s, r) => s + r.amount, 0);
  y = pdfSectionTitle(doc, y, pageW, "Summary");
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: "Total spend", value: money(total), accent: PDF_WARN },
    { label: "Approved expenses", value: approved.length, accent: PDF_LEAF },
    { label: "All entries", value: rows.length, accent: PDF_GOLD },
  ]);

  const byCategory = new Map<string, number>();
  for (const r of approved) byCategory.set(r.category, (byCategory.get(r.category) ?? 0) + r.amount);
  if (byCategory.size > 0) {
    y = pdfSectionTitle(doc, y, pageW, "By category");
    y = pdfSimpleTable(doc, y, pageW, ["CATEGORY", "AMOUNT"], [...byCategory.entries()].sort((a, b) => b[1] - a[1]).map(([c, a]) => [c, money(a)]), [0.7, 0.3]);
  }

  y = pdfSectionTitle(doc, y, pageW, "Transactions");
  y = pdfSimpleTable(
    doc,
    y,
    pageW,
    ["DATE", "CATEGORY", "LOGGED BY", "METHOD", "STATUS", "AMOUNT"],
    rows.map((r) => [fmtDate(r.expenseDate), r.category, r.loggedByName ?? "—", r.paymentMethod, r.status, money(r.amount)]),
    [0.15, 0.22, 0.2, 0.13, 0.12, 0.18],
  );

  pdfReportFooter(doc, companyName);
  pdfGeneratedStamp(doc, generatedBy);
  return doc;
}

export async function buildCommissionReportRangePdf(range: DateRange, rows: CommissionReportRow[], companyName: string, generatedBy: string | null | undefined, logoImage: string | null): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoImage);
  let y = header(doc, "Commission Report", range, companyName, generatedBy, logo);

  const total = rows.reduce((s, r) => s + r.total, 0);
  y = pdfSectionTitle(doc, y, pageW, "Summary");
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: "Total commission", value: money(total), accent: PDF_GOLD },
    { label: "Months covered", value: new Set(rows.map((r) => r.month)).size, accent: PDF_LEAF },
  ]);

  y = pdfSectionTitle(doc, y, pageW, "By agent, by month");
  y = pdfSimpleTable(doc, y, pageW, ["MONTH", "AGENT", "PERSONAL", "POOL", "TOTAL"], rows.map((r) => [r.month, r.agentName, money(r.personal), money(r.poolShare), money(r.total)]), [0.15, 0.3, 0.2, 0.17, 0.18]);

  pdfReportFooter(doc, companyName);
  pdfGeneratedStamp(doc, generatedBy);
  return doc;
}

export async function buildPayrollReportPdf(range: DateRange, rows: PayrollReportRow[], companyName: string, generatedBy: string | null | undefined, logoImage: string | null): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoImage);
  let y = header(doc, "Payroll Report", range, companyName, generatedBy, logo);

  const total = rows.reduce((s, r) => s + r.net, 0);
  y = pdfSectionTitle(doc, y, pageW, "Summary");
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: "Total net pay", value: money(total), accent: PDF_OK },
    { label: "Payroll runs", value: new Set(rows.map((r) => r.period)).size, accent: PDF_LEAF },
  ]);

  y = pdfSectionTitle(doc, y, pageW, "By period, by staff");
  y = pdfSimpleTable(doc, y, pageW, ["PERIOD", "STAFF", "STATUS", "NET PAY"], rows.map((r) => [r.period, r.staffName, r.status.replace("_", " "), money(r.net)]), [0.2, 0.4, 0.2, 0.2]);

  pdfReportFooter(doc, companyName);
  pdfGeneratedStamp(doc, generatedBy);
  return doc;
}

export async function buildSummaryReportPdf(
  range: DateRange,
  collected: number,
  expensesTotal: number,
  commissionTotal: number,
  payrollTotal: number,
  companyName: string,
  generatedBy: string | null | undefined,
  logoImage: string | null,
): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const logo = await loadLogo(logoImage);
  let y = header(doc, "Financial Summary", range, companyName, generatedBy, logo);

  const net = collected - expensesTotal - commissionTotal - payrollTotal;
  y = pdfSectionTitle(doc, y, pageW, "Income statement");
  y = pdfSimpleTable(
    doc,
    y,
    pageW,
    ["LINE", "AMOUNT"],
    [
      ["Collected (revenue)", money(collected)],
      ["Expenses", `(${money(expensesTotal)})`],
      ["Commission paid", `(${money(commissionTotal)})`],
      ["Payroll paid", `(${money(payrollTotal)})`],
      ["Net", money(net)],
    ],
    [0.6, 0.4],
  );

  pdfReportFooter(doc, companyName);
  pdfGeneratedStamp(doc, generatedBy);
  return doc;
}
