import { jsPDF } from 'jspdf';
import { ghs } from '../../../shared/lib/format';
import { pdfAccentStatRow, pdfBarChart, pdfBrandedHeader, pdfReportFooter, pdfSectionTitle, pdfSimpleTable, PDF_DANGER, PDF_GOLD, PDF_LEAF, PDF_OK, PDF_PALETTE } from '../../../shared/lib/pdfReport';
import type { ReportRange } from '../../manager/lib/managementReportLogic';
import type { StaffSalesRow } from '../lib/staffReportLogic';

const DAY_LABELS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

// Port of index.html's buildStaffReportPDF() (index.html:23384-23450).
// The Operations section (assigned/completed/overdue/escalated) is
// dropped -- see staffReportLogic.ts's own comment for exactly why
// (needs task-lifecycle data web-next's schema doesn't have). Photo-or-
// initials profile circle also dropped -- web-next's Profile has no
// on-file avatar field ported yet.
export function buildStaffReportPdf(rows: StaffSalesRow[], one: StaffSalesRow | null, dayOfWeek: number[] | null, staffKey: string, range: ReportRange, generatedByName: string, companyName: string | null | undefined, logoDataUri: string | null): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const rightLines = [`Generated by ${generatedByName}`, new Date().toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })];

  if (!staffKey) {
    let y = pdfBrandedHeader(doc, 'STAFF REPORT', `All staff comparison  ·  ${range.label}`, rightLines, logoDataUri);
    y += 6;
    y = pdfSectionTitle(doc, y, pageW, 'Comparison', `${rows.length} staff`);
    if (rows.length) {
      y = pdfBarChart(
        doc,
        12,
        y,
        pageW - 24,
        38,
        rows.slice(0, 8).map((s, i) => ({ label: s.name, value: Math.round(s.revenue), color: PDF_PALETTE[i % PDF_PALETTE.length] })),
      );
      y = pdfSimpleTable(
        doc,
        y,
        pageW,
        ['STAFF', 'LEADS ADDED', 'DEALS CLOSED', 'REVENUE', 'TASKS DONE (90D)', 'SITE VISITS'],
        rows.map((s) => [s.name, String(s.leadsAdded), String(s.dealsClosed), ghs(s.revenue), String(s.tasksCompleted), String(s.siteVisits)]),
        [0.26, 0.14, 0.14, 0.18, 0.15, 0.13],
      );
    }
    pdfReportFooter(doc, companyName);
    return doc;
  }

  const row = one ?? { key: staffKey, name: staffKey, leadsAdded: 0, dealsClosed: 0, revenue: 0, siteVisits: 0, tasksCompleted: 0, avgTaskDays: null, daysAttended: 0, onTimeDays: 0 };
  let y = pdfBrandedHeader(doc, 'STAFF REPORT', `${row.name}  ·  ${range.label}`, rightLines, logoDataUri);
  y += 6;

  y = pdfSectionTitle(doc, y, pageW, 'Pipeline activity', range.label);
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'Leads added', value: row.leadsAdded, accent: PDF_LEAF },
    { label: 'Deals closed', value: row.dealsClosed, accent: PDF_OK },
    { label: 'Revenue collected', value: ghs(row.revenue), accent: PDF_GOLD },
    { label: 'Site visits', value: row.siteVisits, accent: PDF_LEAF },
  ]);

  y = pdfSectionTitle(doc, y, pageW, 'Tasks & attendance', 'last 90 days');
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'Tasks completed', value: row.tasksCompleted, accent: PDF_OK },
    { label: 'Avg days to close', value: row.avgTaskDays != null ? row.avgTaskDays.toFixed(1) : '—', accent: PDF_LEAF },
    { label: 'Days attended', value: row.daysAttended, accent: PDF_OK },
    { label: 'On-time days', value: row.onTimeDays, accent: row.onTimeDays < row.daysAttended ? PDF_DANGER : PDF_OK },
  ]);

  if (dayOfWeek) {
    y = pdfSectionTitle(doc, y, pageW, 'Time on system by day of week');
    y = pdfBarChart(
      doc,
      12,
      y,
      pageW - 24,
      36,
      dayOfWeek.map((v, i) => ({ label: DAY_LABELS[i], value: v, color: PDF_PALETTE[i % PDF_PALETTE.length] })),
    );
  }

  pdfReportFooter(doc, companyName);
  return doc;
}

export function staffReportFilename(staffKey: string, range: ReportRange): string {
  return `Staff_Report_${staffKey || 'All'}_${range.from}_to_${range.to}.pdf`;
}
