import { jsPDF } from 'jspdf';
import { ghs } from '../../../shared/lib/format';
import { pdfAccentStatRow, pdfBarChart, pdfBrandedHeader, pdfCompositionBar, pdfLineChart, pdfReportFooter, pdfSectionTitle, pdfSimpleTable, PDF_LEAF, PDF_MUTED, PDF_OK, PDF_PALETTE, PDF_WARN } from '../../../shared/lib/pdfReport';
import { pctChangeStr, type ManagementReportData, type ReportRange } from './managementReportLogic';

// Port of index.html's buildManagementReportPDF() (index.html:22969-
// 23054). Two sections dropped, both documented on ManagementReportData
// itself: Expenses (period)/Net cash position (needs the live-only
// Expenses tables) and Expenses by category (same reason).
export function buildManagementReportPdf(range: ReportRange, d: ManagementReportData, prior: ReportRange | null, priorData: ManagementReportData | null, generatedByName: string, companyName: string | null | undefined, logoDataUri: string | null): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  let y = pdfBrandedHeader(
    doc,
    'MANAGEMENT REPORT',
    `${range.label}  ·  ${range.from} to ${range.to}`,
    [`Generated by ${generatedByName}`, new Date().toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })],
    logoDataUri,
  );
  y += 6;

  y = pdfSectionTitle(doc, y, pageW, 'Executive summary');
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'New leads', value: d.newLeadsCount, accent: PDF_LEAF },
    { label: 'Revenue collected', value: ghs(d.revenue), accent: PDF_OK },
    { label: 'Site visits', value: d.visitsInRange, accent: PDF_LEAF },
    { label: 'Fully paid', value: d.fullyPaidCount, accent: PDF_OK },
  ]);
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'Outstanding balance', value: ghs(d.outstandingTotal), accent: PDF_WARN },
    { label: 'Pending approvals', value: d.pendingPayments + d.pendingFundRequests, accent: d.pendingPayments + d.pendingFundRequests ? PDF_WARN : PDF_OK },
  ]);
  y += 2;

  if (priorData && prior) {
    y = pdfSectionTitle(doc, y, pageW, `vs. ${prior.label}`);
    y = pdfSimpleTable(
      doc,
      y,
      pageW,
      ['METRIC', 'THIS PERIOD', 'PREVIOUS PERIOD', 'CHANGE'],
      [
        ['New leads', String(d.newLeadsCount), String(priorData.newLeadsCount), pctChangeStr(priorData.newLeadsCount, d.newLeadsCount)],
        ['Revenue collected', ghs(d.revenue), ghs(priorData.revenue), pctChangeStr(priorData.revenue, d.revenue)],
        ['Site visits', String(d.visitsInRange), String(priorData.visitsInRange), pctChangeStr(priorData.visitsInRange, d.visitsInRange)],
      ],
      [0.34, 0.22, 0.22, 0.22],
    );
  }

  if (y > 210) {
    doc.addPage();
    y = 16;
  }
  y = pdfSectionTitle(doc, y, pageW, 'Revenue trend', 'last 6 months');
  y = pdfLineChart(doc, 12, y, pageW - 24, 42, d.revenueTrend);
  if (d.forecastNextMonth != null) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(...PDF_MUTED);
    doc.text(`Projected next month: ~${ghs(d.forecastNextMonth)} (3-month trend, not a promise)`, 12, y);
    doc.setTextColor(20, 20, 20);
    y += 8;
  }

  if (y > 230) {
    doc.addPage();
    y = 16;
  }
  y = pdfSectionTitle(doc, y, pageW, 'Pipeline composition', d.pipelineComposition.healthLabel);
  if (d.pipelineComposition.totalVal > 0) {
    y = pdfCompositionBar(doc, 12, y, pageW - 24, [
      { label: 'Committed (paying)', value: d.pipelineComposition.committedVal, color: PDF_OK, fmt: ghs },
      { label: 'Prospects (unpaid)', value: d.pipelineComposition.prospectVal, color: [148, 163, 184], fmt: ghs },
    ]);
  } else {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text('No active pipeline data.', 12, y);
    doc.setTextColor(20, 20, 20);
    y += 10;
  }
  y += 2;

  if (y > 210) {
    doc.addPage();
    y = 16;
  }
  y = pdfSectionTitle(doc, y, pageW, 'Agent performance (period)');
  if (d.perAgent.length) {
    y = pdfBarChart(
      doc,
      12,
      y,
      pageW - 24,
      38,
      d.perAgent.slice(0, 6).map((a, i) => ({ label: a.name, value: Math.round(a.revenue), color: PDF_PALETTE[i % PDF_PALETTE.length] })),
    );
    y = pdfSimpleTable(
      doc,
      y,
      pageW,
      ['AGENT', 'NEW LEADS', 'REVENUE COLLECTED'],
      d.perAgent.map((a) => [a.name, String(a.newLeads), ghs(a.revenue)]),
      [0.5, 0.2, 0.3],
    );
  } else {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text('No agent activity in this period.', 12, y);
    doc.setTextColor(20, 20, 20);
    y += 10;
  }

  if (y > 230) {
    doc.addPage();
    y = 16;
  }
  y = pdfSectionTitle(doc, y, pageW, 'Payments by method (period)');
  if (d.byMethod.length) {
    y = pdfCompositionBar(
      doc,
      12,
      y,
      pageW - 24,
      d.byMethod.map((m, i) => ({ label: m.method, value: m.total, color: PDF_PALETTE[i % PDF_PALETTE.length], fmt: ghs })),
    );
    y = pdfSimpleTable(
      doc,
      y,
      pageW,
      ['METHOD', 'COUNT', 'TOTAL'],
      d.byMethod.map((m) => [m.method, String(m.count), ghs(m.total)]),
      [0.5, 0.2, 0.3],
    );
  } else {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text('No payments recorded in this period.', 12, y);
    doc.setTextColor(20, 20, 20);
    y += 10;
  }

  pdfReportFooter(doc, companyName);
  return doc;
}

export function managementReportFilename(range: ReportRange): string {
  return `Management_Report_${range.from}_to_${range.to}.pdf`;
}
