import { useState } from 'react';
import { useAllLeads } from '../../payments/hooks/useLogPayment';
import { useCanFulfilContracts } from '../hooks/useContractRequests';
import { useContracts, useGenerateContract } from '../hooks/useContracts';
import { computeLeadQuotationTotals } from '../../quotation/lib/quotationLogic';
import { useConfig } from '../../manager/hooks/useConfigSettings';
import { ghs } from '../../../shared/lib/format';
import type { Lead } from '../../../types/domain';
import styles from './ContractGeneratorScreen.module.css';

// Standalone generator for the real Contract of Sale PDF (index.html's
// buildContractOfSalePDF -- a long legal document, distinct from the
// request/fulfil workflow ContractRequestsScreen models). Gated the same
// way canManageContracts() gates the real "Contract of Sale APP":
// manager or the 'elizabeth' key only, matching contracts_ins RLS.
export function ContractGeneratorScreen() {
  const canGenerate = useCanFulfilContracts();

  if (!canGenerate) {
    return (
      <div className={styles.wrap}>
        <h1 className={styles.title}>Generate Contract</h1>
        <p className={styles.sub}>You don&apos;t have access to this. Ask a manager if you need it.</p>
      </div>
    );
  }
  return <ContractGeneratorInner />;
}

function ContractGeneratorInner() {
  const { data: leads } = useAllLeads();
  const { data: contracts, isLoading: contractsLoading } = useContracts();
  const [query, setQuery] = useState('');
  const [selectedLead, setSelectedLead] = useState<Lead | null>(null);

  const q = query.trim().toLowerCase();
  const matches = q ? (leads ?? []).filter((l) => l.name.toLowerCase().includes(q) || l.contact.includes(q)).slice(0, 8) : [];

  return (
    <div className={styles.wrap}>
      <h1 className={styles.title}>Generate Contract</h1>
      <p className={styles.sub}>Search a client and generate their branded Contract of Sale PDF -- the full legal document, pricing, KYC and all.</p>

      <div className={styles.card}>
        {!selectedLead ? (
          <>
            <input className={styles.input} placeholder="Search any client by name or contact…" value={query} onChange={(e) => setQuery(e.target.value)} />
            {matches.length > 0 && (
              <div className={styles.pickerList}>
                {matches.map((l) => (
                  <button key={l.id} type="button" className={styles.pickerRow} onClick={() => setSelectedLead(l)}>
                    <div className={styles.pickerName}>{l.name}</div>
                    <div className={styles.pickerMeta}>
                      {l.contact} · {l.plotType} · {l.paymentPlan}
                    </div>
                  </button>
                ))}
              </div>
            )}
            {q && matches.length === 0 && <p style={{ color: 'var(--muted)', fontSize: 12.5, marginTop: 10 }}>No clients match &quot;{query}&quot;.</p>}
          </>
        ) : (
          <SelectedLeadPreview lead={selectedLead} onChange={() => setSelectedLead(null)} />
        )}
      </div>

      <div className={styles.sectitle}>Previously generated</div>
      {contractsLoading && <p style={{ color: 'var(--muted)' }}>Loading…</p>}
      {contracts && contracts.length === 0 && !contractsLoading && <p style={{ color: 'var(--muted)', fontSize: 12.5 }}>No contracts generated yet.</p>}
      <div className={styles.list}>
        {contracts?.map((c) => (
          <div className={styles.row} key={c.id}>
            <div>
              <div className={styles.name}>{c.clientName}</div>
              <div className={styles.meta}>
                Generated by {c.createdByName} · {c.createdAt.slice(0, 10)}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function SelectedLeadPreview({ lead, onChange }: { lead: Lead; onChange: () => void }) {
  const { data: config } = useConfig();
  const generate = useGenerateContract();
  const totals = config ? computeLeadQuotationTotals(config, lead) : null;
  const hasKyc = !!lead.kyc && Object.values(lead.kyc).some((v) => v);

  return (
    <div>
      <div className={styles.selectedHead}>
        <div>
          <div className={styles.pickerName}>{lead.name}</div>
          <div className={styles.pickerMeta}>
            {lead.contact} · {lead.plotType} · {(lead.noPlots || 1)} plot(s)
          </div>
        </div>
        <button type="button" className={styles.changeBtn} onClick={onChange}>
          Change
        </button>
      </div>

      {totals && (
        <>
          <div className={styles.summaryRow}>
            <span className={styles.summaryLabel}>Agreed price</span>
            <span className={styles.summaryVal}>{ghs(totals.grand)}</span>
          </div>
          <div className={styles.summaryRow}>
            <span className={styles.summaryLabel}>Amount paid</span>
            <span className={styles.summaryVal}>{ghs(lead.amtPaid)}</span>
          </div>
          {totals.planMonths > 0 && (
            <div className={styles.summaryRow}>
              <span className={styles.summaryLabel}>Monthly due ({totals.planMonths} months)</span>
              <span className={styles.summaryVal}>{ghs(totals.monthlyDue)}</span>
            </div>
          )}
        </>
      )}

      {!hasKyc && <p className={styles.kycNote}>No KYC details captured for this client yet -- those fields will render blank on the PDF, ready to be filled in by hand.</p>}

      <button type="button" className={styles.genBtn} disabled={generate.isPending || !config} onClick={() => generate.mutate(lead)}>
        {generate.isPending ? 'Generating…' : '📄 Generate & download PDF'}
      </button>
    </div>
  );
}
