import { jsPDF } from 'jspdf';
import { ghs, monthLabel, shiftMonth } from '../../../shared/lib/format';
import { pdfAccentStatRow, pdfBarChart, pdfBrandedHeader, pdfReportFooter, pdfSectionTitle, pdfSimpleTable, PDF_GOLD, PDF_LEAF, PDF_OK, PDF_PALETTE } from '../../../shared/lib/pdfReport';
import type { CompanyCommissionReport } from '../../../types/domain';

// Faithful port of index.html's buildCommissionReportPDF() (index.html:
// 25507-25537) -- pool summary stat cards, a top-8 earners bar chart, and
// the full per-agent breakdown table, all built from the shared branded-
// report toolkit (see shared/lib/pdfReport.ts).
export function buildCommissionReportPdf(data: CompanyCommissionReport, generatedByName: string, companyName: string | null | undefined, logoDataUri: string | null): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  let y = pdfBrandedHeader(
    doc,
    'COMMISSION REPORT',
    monthLabel(data.monthKey) + '  ·  payable ' + shiftMonth(data.monthKey, 1) + '-15',
    ['Generated by ' + generatedByName, new Date().toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })],
    logoDataUri,
  );
  y += 6;

  const grandTotal = data.rows.reduce((s, r) => s + r.total, 0);
  y = pdfSectionTitle(doc, y, pageW, 'Pool summary');
  y = pdfAccentStatRow(doc, y, pageW, [
    { label: 'New plots sold', value: data.totalNewPlotsThisMonth, accent: PDF_LEAF },
    { label: 'Pool total', value: ghs(data.poolTotal), accent: PDF_GOLD },
    { label: 'Eligible agents', value: data.eligibleCount, accent: PDF_LEAF },
    { label: 'Total payable', value: ghs(grandTotal), accent: PDF_OK },
  ]);

  if (data.rows.length) {
    y = pdfSectionTitle(doc, y, pageW, 'By agent — earnings breakdown');
    y = pdfBarChart(
      doc,
      12,
      y,
      pageW - 24,
      38,
      data.rows
        .slice()
        .sort((a, b) => b.total - a.total)
        .slice(0, 8)
        .map((r, i) => ({ label: r.name, value: Math.round(r.total), color: PDF_PALETTE[i % PDF_PALETTE.length] })),
    );
  }
  y = pdfSectionTitle(doc, y, pageW, 'By agent — detail');
  y = pdfSimpleTable(
    doc,
    y,
    pageW,
    ['AGENT', 'NEW PLOTS', 'PERSONAL', 'POOL', 'TOTAL'],
    data.rows.map((r) => [r.name, String(r.newPlotsThisMonth), ghs(r.personal), r.eligible ? ghs(r.poolShare) : '—', ghs(r.total)]),
    [0.32, 0.15, 0.18, 0.17, 0.18],
  );

  pdfReportFooter(doc, companyName);
  return doc;
}

export function commissionReportFilename(monthKey: string): string {
  return `PEP_Commission_${monthKey}.pdf`;
}
